---
title: "STAT 305 Quiz I Summary"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, error = FALSE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
```

```{r echo=FALSE, cache=FALSE, include = FALSE}
   mode_values <- function(x){
      tbl <- table(x)
      names(which(tbl == max(tbl)))
   }

   print_multiple <- function(x){
      if(length(x) == 1){
         x
      }else{
         xfirst <- x[1:(length(x)-1)]
         paste(paste0(xfirst,collapse = ", "),"and",x[length(x)])
      }
   }

   my_quantile <- function(p,x){
      x <- x[order(x)]
      
      n <- length(x)

      raw.i <- n*p + .5
      floor.i <- floor(raw.i)
      if(floor.i == raw.i){
         x[floor.i]
      }else{
         x[floor.i] + (n*p - floor.i + .5)*(x[floor.i+1] - x[floor.i])
      }
   }
```

### Exam Summary

```{r}
df<-readr::read_csv( "stat305.spring20.grades.csv")

df<- df %>% filter(`Quiz 1` > 0) %>% mutate(`Quiz 1`=as.numeric(`Quiz 1`))

```
#### Top 5 grades
```{r}
head(sort(df$`Quiz 1`, decreasing = T),5) %>% round(2)
```
#### Quantiles
```{r}
summary(df$`Quiz 1`)
```



```{r, fig.height= 6}

p1<-df %>% ggplot(aes(x=`Quiz 1`))+geom_histogram(binwidth = 2)+theme(panel.background = element_rect(fill = "lightgray", colour = "#6D9EC1", size = 2, linetype = "solid")) + theme_bw()

# p2<-df %>% ggplot(aes(y=Quiz1))+geom_boxplot(width=1 )+theme(panel.background = element_rect(fill = "lightgray", colour = "#6D9EC1", size = 2, linetype = "solid"))+ coord_flip()


p= seq(0.1,1, length.out = length(df$`Quiz 1`))
qp<-my_quantile(p,x =  df$`Quiz 1`)

df1<- data.frame(p, qp)
names(df1)<- c( "p", "Q(p)")
library(magrittr)
library(ggplot2)
p2<-df1 %>% ggplot(aes(x = p, y = `Q(p)`))+ geom_point()+ylim(70,100)+theme_bw()



gridExtra::grid.arrange(p1, p2, nrow=2)

```







