---
title: "STAT 305: Lecture 5"
author: "Amin Shirazi"
date: "`r Sys.Date()`"

output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
name: inverse
layout: true
class: center, middle, inverse
---
# STAT 305: Lecture 5
## Chapter 3: Elementary Descriptive Statistics
.footnote[Course page: [ashirazist.github.io/stat305.github.io](https://ashirazist.github.io/stat305.github.io)]
---
# Leftovers from Lecture 4
---
layout:false
.left-column[
## Summarizing
### Purpose
### Simple Graphs
### Freq Tables
]
.right-column[
### Frequency Tables
```
              Group 1             Group 2
            74 79 77 81         65 77 78 74
            68 79 81 76         76 73 71 71
            81 80 80 78         86 81 76 89
            88 83 79 91         79 78 77 76
            79 75 74 73         72 76 75 79    
```

- **Class**: A grouping of the observations

- **Frequency**: The number of observations in a class

- **Relative Frequency**: The proportion of the observations in the class

- **Cumulative Relative Frequency**: The proportion of observations in the current class or a previous class.
]
---
layout:false
.left-column[
## Summarizing
### Purpose
### Simple Graphs
### Freq Tables
### Histograms
]
.right-column[
### Histograms
```
              Group 1             Group 2
            74 79 77 81         65 77 78 74
            68 79 81 76         76 73 71 71
            81 80 80 78         86 81 76 89
            88 83 79 91         79 78 77 76
            79 75 74 73         72 76 75 79    
```


A **histogram** is essentially a graphical representation of a frequency table.

**Tips for useful frequency tables**

1. Use equal class intervals
2. When the goal is to compare multiple groups, use uniform scales on each graph (i.e., keep lengths consistent)
3. Show the entire vertical axis (especially for relative frequency histograms)
]
---
layout: true
class: center, middle, inverse
---
# Continuing
